package model;
// Generated 02-mar-2018 9:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sudoku generated by balsamiq
 */
public class Sudoku  implements java.io.Serializable {

     private Integer idsudoku;
     private Integer level;
     private String description;
     private String problem;
     private String solution;
     private Set histories = new HashSet(0);

    public Sudoku() {
    }
    public Sudoku(Integer level, String description, String problem, String solution) {
        this.level = level;
        this.description = description;
        this.problem = problem;
        this.solution = solution;
    }
    public Integer getIdsudoku() {
        return this.idsudoku;
    }
    public void setIdsudoku(Integer idsudoku) {
        this.idsudoku = idsudoku;
    }
    public Integer getLevel() {
        return this.level;
    }
    public void setLevel(Integer level) {
        this.level = level;
    }
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public String getProblem() {
        return this.problem;
    }
    public void setProblem(String problem) {
        this.problem = problem;
    }
    public String getSolution() {
        return this.solution;
    }
    public void setSolution(String solution) {
        this.solution = solution;
    }
    public Set getHistories() {
        return this.histories;
    }
    public void setHistories(Set histories) {
        this.histories = histories;
    }
    @Override
    public String toString() {
        return "Sudoku{" + "idsudoku=" + idsudoku + ", level=" + level + ", description=" + description + ", problem=" + problem + ", solution=" + solution + ", histories=" + histories + '}';
    }
}


