package model;
// Generated 02-mar-2018 9:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String name;
     private String password;
     private Set histories = new HashSet(0);

    public User() {
    }

    public User(String username, String name, String password) {
        this.username = username;
        this.name = name;
        this.password = password;
    }
    

	
    public User(String username) {
        this.username = username;
    }

    
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getHistories() {
        return this.histories;
    }
    
    public void setHistories(Set histories) {
        this.histories = histories;
    }

    @Override
    public String toString() {
        return "User{" + "username=" + username + ", name=" + name + ", password=" + password + ", histories=" + histories + '}';
    }




}


